CREATE TABLE PERSON (
  ID INT NOT NULL AUTO_INCREMENT,
  AGE INT,
  GENDER VARCHAR(255),
  EDUCATION_LEVEL VARCHAR(255),
  JOB_TITLE VARCHAR(255),
  YEARS_OF_EXPERIENCE DOUBLE,
  SALARY DOUBLE,
  PRIMARY KEY (ID)
);